### ISSUE TITLE
libudev-zero crushes sway upon using x11 application

### ISSUE THREAD

**Issue by keleset** [illiliti/libudev-zero#17]
So, everything that uses wayland works perfectly fine.
As soon as I open any app using x11 (xwayland) - sway crashes.

Here is `sway -V -d` output. 
https://pastebin.com/g2bmmQmc
I launch alacritty and then `mpv --gpu-context=x11egl afile.mkv`

The issue is not present if I switch to eudev.
Setup - Alpine on laptop with integrated and dedicated AMD graphics.
I was unable to detect anything unusual while using gdb with sway, but I'm willing to use gdb again if you tell me how and what should I use it with.

**Comment by illiliti** [comment]
Does the issue persist if you downgrade to previous version 0.4.7?

**Comment by keleset** [comment]
Yes, it does. And even before that, I've previously tried libudev-zero, but didn't have time to debug it and quickly gave up back then, not sure what version it was...

**Comment by illiliti** [comment]
Can you apply this PR https://github.com/swaywm/wlroots/pull/2626 to wlroots and then trigger the crash?

**Comment by keleset** [comment]
I've built master branch of sway & wlroots and issue seems to be gone now. Guess that was a sway/wlroots bug after all.
