### ISSUE TITLE
bluez support

### ISSUE THREAD

**Issue by keleset** [illiliti/libudev-zero#19]
Is it possible to make libudev-zero work with bluez or maybe develop some instructions to work it around? Bluetoothctl is unable to find any bluetooth controllers.

**Comment by illiliti** [comment]
Bluez uses `udev_hwdb` API which is not yet implemented. Possible workaround is compiling bluez without udev support.

```
./configure --disable-udev
make
```

**Comment by keleset** [comment]
bluez still seem unable to detect bluetooth controller, even if built with `--disable-udev`

**Comment by illiliti** [comment]
Can you send me exact error with and without libudev-zero?

**Comment by keleset** [comment]
There is no error actually, I'm just unable to detect any bluetooth adapters with bluez, even though `rfkill list` sees them perfectly fine.

**Comment by keleset** [comment]
A bit more research revealed that a firmware file for the bt device was missing, fixed now.
BTW, thousand kudos for libudev-zero! Thing is, actually, an outstanding replacement for udev, great job!
