### ISSUE TITLE
Sway segfaults when 'pkill sway'

### ISSUE THREAD

**Issue by sdsddsd1** [illiliti/libudev-zero#2]
The following happens with `sway 1.5` and `wlroots 0.11.0`. It happens sometimes, but not everytime.  
When I do 'pkill sway' it crashes with a segfault when switching back to tty and leaves the computer in a unresponsive state. No more keyboard input is possible. However I can ssh into that machine and do a reboot. This way I will try to get some information through gdb soon.

**Comment by illiliti** [comment]
Should be fixed in latest master

**Comment by sdsddsd1** [comment]
Commit [a5d5e4dd2b2f9611cec337c08225f9c42f7d0978](https://github.com/illiliti/libudev-zero/commit/a5d5e4dd2b2f9611cec337c08225f9c42f7d0978) seems to have it fixed.
