### ISSUE TITLE
udev_device_get_sysattr_value: return value is truncated at \n

### ISSUE THREAD

**Issue by doominator42** [illiliti/libudev-zero#25]
The method [udev_device_get_sysattr_value](https://github.com/illiliti/libudev-zero/blob/1fd071f24e80062526bd89f8b2941527e8933bb2/udev_device.c#L250) truncates the return value at '\n' which breaks USB/IP because `/sys/devices/platform/vhci_hcd.0/status` has multiple lines.

The [udev implementation](https://github.com/systemd/systemd/blob/5efbd0bf897a990ebe43d7dc69141d87c404ac9a/src/libudev/libudev-device.c#L741) returns the entire content instead (with a maximum size of 4MiB).

With the following change, USB/IP started working.
```diff
diff --git a/udev_device.c b/udev_device.c
index 92c1a41..15a8e0b 100644
--- a/udev_device.c
+++ b/udev_device.c
@@ -247,7 +247,7 @@ const char *udev_device_get_sysattr_value(struct udev_device *udev_device, const
         return NULL;
     }

-    if ((pos = memchr(data, '\n', len))) {
+    if ((pos = memchr(data, '\0', len))) {
         len = pos - data;
     }
```

I think reading the entire file as udev does would be the correct solution.
Please let me know if my thinking is correct or if I'm missing something.

**Comment by illiliti** [comment]
Fixed! Thanks!
