### ISSUE TITLE
RFC: Migrate to automake and autoconf from standalone Makefile

### ISSUE THREAD

**Issue by watatuki** [illiliti/libudev-zero#28]
Hi  illiliti.

I think libudev-zero is good solution for linux container guest.  I respect to your work.
Current libudev-zero build by standalone Makefile, it's not support build time configuration change such as enabling helper, install mdev support  and etc...
I propose to migrate automake/autoconf from standalone Makefile.  If it fine, I will contribute.

**Comment by illiliti** [comment]
Hi! You're welcome!

Sorry but current Makefile will stay as is. Firstly, autotools are very complicated for such simple use case. Secondly, contrib directory is not intended to be used within build system. This directory is fully detached from main sources and provided only to reference examples such as config files, basic use cases, etc. I suggest you to manually copy/compile(it's very simple) examples from contrib directory.

References:

https://suckless.org/faq
https://softwareengineering.stackexchange.com/q/252053
https://drewdevault.com/2020/06/06/Add-a-contrib-directory.html
