### ISSUE TITLE
Latest version doesn't work with xorg

### ISSUE THREAD

**Issue by phkrl** [illiliti/libudev-zero#30]
After commit 496291 both hotplug and coldplug are broken. Uevents are created properly with proper permissions but xorg doesn't detect input devices at all.
UPD: it doesn't work unless i explicitly specify UDEV_MONITOR_DIR environment variable
UPD2: the exact source of error is line 258: for some reason it is expected that current user can write to UDEV_MONITOR_DIR. If i remove W_OK from access(), input detection works again

**Comment by illiliti** [comment]
Thanks for detailed report. We definitely need unit testing to prevent such issues.
