### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by rnrkrft** [illiliti/libudev-zero#47]
Possible to work on any MacOS?

Depends on:
linux/input.h
sys/sysmacros.h

The sysmacros.h is no problem, but the input.h 
Any idea, what to do, to bring this to a Mac?

Thank's anyway...

**Comment by illiliti** [comment]
Unfortunately, it's not possible. libudev-zero depends on various linuxisms such as sysfs, evdev, netlink, ... You have to rewrite libudev-zero to use MacOS equivalent interfaces if you really need libudev.
