### ISSUE TITLE
NetBSD libxdev

### ISSUE THREAD

**Issue by firasuke** [illiliti/libudev-zero#58]
Hey there,

I stumbled upon [libxdev](https://github.com/krytarowski/libxdev) from NetBSD, and I was wondering how does it compare with libudev-zero?

Thanks in advance!

**Comment by illiliti** [comment]
The libxdev provides access to devices via similar but not exact udev API to accelerate porting applications that have hard dependency on it.
The libudev-zero provides access to devices via exact same udev API to appease applications that have hard dependency on it while being compatible with any device manager, not only systemd-udevd.

BTW I was participating in libxdev creation.
